/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class app_update_service_AppBsDiff */

#ifndef _Included_app_update_service_AppBsDiff
#define _Included_app_update_service_AppBsDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_update_service_AppBsDiff
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_app_update_service_AppBsDiff_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
